### PR TITLE
Added github templates and editorconfig

### PR DESCRIPTION
**Pull request by dsebastien**
Added github templates for issues and pull requests
Added an editorconfig file

### CODE REVIEW

**Comment by michielbdejong** [comment]
Not so sure about the github templates, it's going to be mainly us creating issues ourselves, and then we usually know when to use the current/expected/reproduce format, when to add environment info, etc.

**Comment by dsebastien** [comment]
Indeed, that should remain true for a while ;-)

**Comment by michielbdejong** [comment]
@dsebastien is it ok if we close this? I'm really happy with your contributions re Jest, Greenkeeper, Coveralls, and Prettifier, but not so convinced by these two additions.

**Comment by dsebastien** [comment]
Sure, go ahead.

**Pull request closed without merging**
